config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'
  get '/team', to: 'home#team', as: 'team'
  get '/research', to: 'home#research', as: 'research'
  get '/publications', to: 'home#publications', as: 'publications'
  get '/jobs', to: 'home#jobs', as: 'jobs'
  get '/redcap', to: 'home#redcap', as: 'redcap'
  get '*path', to: 'error#error_404', via: :all, as: 'error'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates_presence_of :job_title
  validates_presence_of :contact_email
  validates_presence_of :job_description
end

app/models/paper.rb
class Paper < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :author
  validates_presence_of :pubdate
  validates_presence_of :pmid
  validates_presence_of :publication
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable

  def is_redcap_permitted?
    self.can_view_redcap == true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActionController::RoutingError, with: -> { render_404 }

  def render_404
    respond_to do |format|
      format.html { render template: 'errors/not_found', status: :not_found }
      format.all { render nothing: true, status: :not_found }
    end
  end
end

app/controllers/error_controller.rb
class ErrorController < ApplicationController
  def error_404
    render 'error/not_found'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def team

  end

  def research

  end

  def publications
    @papers = Paper.all.order("pubdate DESC")
  end

  def jobs
    @jobs = Job.all
  end

  def redcap
    # if !current_user || !current_user.is_redcap_permitted?
    #   redirect_to '/error#error_404'
    # end
    @api_params = { token: ENV[:REDCAP_TOKEN], :format => 'json', :content => 'record', :type => 'flat', :returnFormat => 'json' }
    @url = ''
    # @api_results = HTTParty.post(@url, :body => @api_params)
    # puts @api_results.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container-fluid">
  <div class="row" id="index-title-card">
    <h1 class="col-lg-12 text-center" id="index-title-card-header"></h1>
  </div>
  <hr>
  <br>
  <div class="row">
    <div class="col-lg-10 offset-lg-1 index-text">
      <p>
        The Multiple Sclerosis Genetics Research Laboratory at the Department of Neurology in the UCSF School of Medicine is combining genetics and functional genomics together with immunologic, biochemical,
        neuroimaging and clinical experimental approaches to identify and characterize pathogenic processes of relevance to multiple sclerosis (MS) and other inflammatory conditions of the central nervous system.
      </p>
      <p>
        Neurological impairment in multiple sclerosis is the outcome of a rather extensive and coordinated series of events that include peripheral lymphocyte activation, disruption of the blood-brain barrier, and cellular
        infiltration into the brain parenchyma leading to tissue injury, neurodegeneration, and neurological deficits. The nature and intensity of this process as well as the physiological ability to restore
        homeostasis are conditioned by the unique amino acid sequences that define allelic variants on each of the participating molecules. Genes, either in their germline configuration or as part of complex
        functional networks, play a primary role in determining who is at risk for developing such disorders, how the disease progresses, and how affected individuals responds to therapy.
      </p>
      <p>
        Our goal is to identify the major genetic factors that predispose to autoimmunity in the central nervous system and modulate disease presentation and progression. The availability of highly sensitive
        and high-capacity methods for analysis of gene variation and expression combined with the implementation of algorithms that predict behaviors in complex biological circuits provides an outstanding
        opportunity to facilitate progress in the integration of multiple data sources and functional interpretation of physiological and laboratory results.
      </p>
    </div>
  </div>
</div>

app/views/home/jobs.html.erb
<div class="container-fluid">
  <div class="row" id="jobs-title-card">
    <h1 class="col-lg-12 text-center" id="jobs-title-card-header">Positions Available</h1>
  </div>
  <hr>
  <br>

  <% if @jobs.count > 0 %>

    <br><br>
    <% @jobs.each_with_index do |job, idx| %>
      <div class="row">
        <div class="col-lg-10 offset-lg-1" id=<%= "job#{idx}" %>>
          <h1><%= job[:job_title] %></h1>
          contact: <%= link_to "#{job[:contact_email]}", "mailto:#{job[:contact_email]}" %>
          <br><br>
          <p>
            <%= job[:job_description] %>
          </p>
          <p>
            <%= job[:other_information] %>
          </p>
          <hr>
        </div>
      </div>

    <% end %>

      <div class="row">
        <div class="col-lg-8 offset-lg-2">
          <hr>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <h5 id="jobs-disclaimer" class="text-center">UCSF is an equal opportunity/affirmative action employer. All qualified candidates are encouraged to apply.</h5>
        </div>
      </div>

  <% else %>

    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <br>
        <h3 class="text-center">No positions open at this time</h3>
        <br>
      </div>
    </div>

  <% end %>
</div>

app/views/home/publications.html.erb
<div class="container-fluid">
  <div class="row" id="publications-title-card">
    <h1 class="col-lg-12 text-center" id="publications-title-card-header">Selected Publications</h1>
  </div>
  <hr>
  <% @papers.each_with_index  do |paper, idx| %>

    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <h5><%= paper[:title] %>
          <% if paper[:synopsis].length > 1 %>
            <br>
            <span>
              <a class="abstract-collapse-toggle" id=<%= "abstract#{idx}-collapse-toggle" %> data-toggle="collapse" href=<%= "#abstract#{idx}" %>>
                <span id=<%= "abstract#{idx}-collapse-toggle-prefix" %> class="abstract-toggle-action" ></span>abstract
              </a>
            </span>
          <% end %>
        </h5>
        <% if paper[:synopsis].length > 1 %>
          <div class="collapse" id=<%= "abstract#{idx}" %> >
            <div class="card card-body">
              <%= paper[:synopsis] %>
            </div>
          </div>
        <% end %>
        by: <%= paper[:author] %>
        <br>
        <%= paper[:publication] %>
        <br>
        <%= link_to "PMID: #{paper[:pmid]}", "http://www.ncbi.nlm.nih.gov/pubmed/#{paper[:pmid]}", target: :blank, :class => "pubmed-link"  %>
        <br>
        <hr>
      </div>
    </div>
    <br>

  <% end %>
</div>

app/views/home/redcap.html.erb
<div class="container-fluid">
  <div class="row">
    <h1>Redcap Page</h1>
  </div>

  <div class="row spinner">
    <div class="loader"></div>
  </div>

  <br>

  <div class="row spinner">
    <div class="col-lg-12">
      <h3 class="text-center">Retrieving RedCAP data</h3>
    </div>
  </div>

</div>

app/views/home/team.html.erb
<div class="container-fluid">
  <div class="row" id="team-title-card">
    <h1 class="col-lg-12 text-center" id="team-title-card-header">Who We Are</h1>
  </div>
  <hr>
  <br>

  <div class="row team-block">
    <div class="col-lg-8 offset-lg-2">
      <h3 class="team-header">Jorge Oksenberg, PhD.</h3>
      <h6 class="team-subheader">Principal Investigator</h6>
      <p><%= image_tag("jorge.jpg", :class => "team-thumbnail")%>
        Dr. Oksenberg is the G.A. Zimmermann Endowed Chair in Neurology. As a native from Argentina, Dr. Oksenberg received his Ph.D. in Immunology from the Hebrew University of Jerusalem, Israel, and joined the UCSF
        faculty in 1993 following post-doctoral training at Stanford University. Since 1979 his research has focused in the areas of human immunogenetics and the control of the immune response. He has authored numerous
        publication and scholarly reviews in the field and is a leading investigator in the International Multiple Sclerosis Genetics Consortium.<br><a href="mailto:jorge.oksenberg@ucsf.edu">contact: jorge.oksenberg@ucsf.edu</a>
      </p>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h3 class="team-header">Alessandro Didonna, PhD.</h3>
      <h6 class="team-subheader">Adjunct Assistant Professor</h6>
      <p><%= image_tag("alessandro.jpg", :class => "team-thumbnail")%>
        My main research interest consists in understanding the molecular mechanisms underlying neurodegeneration. I obtained a PhD in Structural and Functional Genomics at the International School for Advanced Studies (Italy),
        where I studied the effects of prion infection on neuronal signaling under the supervision of Dr. Giuseppe Legname. In 2010, I joined the laboratory of Dr. Puneet Opal at Northwestern University, focusing my research
        efforts on the study of the polyglutamine disorder spinocerebellar ataxia type 1 (SCA1) and the rare pediatric disease giant axonal neuropathy (GAN). For my second postdoctoral experience, I joined in 2013 the Multiple
        Sclerosis Genetics Laboratory directed by Dr. Jorge Oksenberg at University of California San Francisco (UCSF) and, since then, I have been working on the functional characterization of the genome wide association study
        (GWAS) data generated in the lab. Additionally, I have been using cutting-edge genomic tools and mouse genetics to understand MS pathophysiology. In 2018, I have transitioned to an Assistant Adjunct Professor position,
        extending my research to the investigation of neurodegenerative processes in progressive MS.<br><a href="mailto:alessandro.didonna@ucsf.edu">contact: alessandro.didonna@ucsf.edu</a>
      </p>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h3 class="team-header">Qin Ma, PhD.</h3>
      <h6 class="team-subheader">Assistant Researcher</h6>
      <p><%= image_tag("qin.png", :class => "team-thumbnail")%>
        Qin joined the group in January 2019 after obtaining her PhD from Beijing Institute of Genomics, Chinese Academy of Sciences. In the Oksenberg lab, her research mainly focuses on understanding the genetic and epigenetic
        regulations in MS. She will combine experiments and bioinformatics to understand the molecular mechanism of MS.<br><a href="mailto:qin.ma@ucsf.edu">contact: qin.ma@ucsf.edu</a>
      </p>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h3 class="team-header">Stacy Caillier</h3>
      <h6 class="team-subheader">Biorepository Manager</h6>
      <p><%= image_tag("stacy.jpg", :class => "team-thumbnail")%>
        Stacy started working with the Multiple Sclerosis Genetics Research Group in July of 1998, after graduating from the University of California, Santa Cruz with a bachelor degree in Neuroscience and Behavior.
        In addition to heading up the DNA genotyping projects, she works in quantitative PCR, and SNP/expression chips. More recently, Stacy is leading the application of immunological assays to assess the functional
        role of genetic variants associated with multiple sclerosis susceptibility and progression.<br><a href="mailto:stacy.caillier@ucsf.edu">contact: stacy.caillier@ucsf.edu</a>
      </p>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h3 class="team-header">Rosa Guerrero</h3>
      <h6 class="team-subheader">Bio-Specimens Technician</h6>
      <p><%= image_tag("rosa.jpg", :class => "team-thumbnail")%>
        Rosa started working with the group in July of 2004 after working at the UCSF DNA Bank. Rosa's primary responsibility is the isolation of high quality nucleic acids from blood samples received from across the
        United States and abroad for genetic studies in multiple sclerosis.<br><a href="mailto:rosa.guerrero@ucsf.edu">contact: rosa.guerrero@ucsf.edu</a>
      </p>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h3 class="team-header">Emily Alvarez</h3>
      <h6 class="team-subheader">Bio-Specimens Technician</h6>
      <p><%= image_tag("emily.jpg", :class => "team-thumbnail")%>
        Emily started working with the Multiple Sclerosis Genetics Research Group in October 2024 as a Laboratory Assistant after
        graduating from the University of California, Berkeley with degrees in Spanish and Molecular and Cell Biology, with an
        emphasis in immunology. In the lab her roles include the isolation of high-quality nucleic acids from blood samples and sample
        storage for genetic clinical and laboratory studies.  <br><a href="emily.alvarez@ucsf.edu">contact: emily.alvarez@ucsf.edu</a>
      </p>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h3 class="team-header">Janet Yau</h3>
      <h6 class="team-subheader">Administrative Support</h6>
      <p><%= image_tag("janet.jpg", :class => "team-thumbnail")%>
        Janet came to us with a Bachelor's Degree in Business Administration and her position covers a wide variety of responsibilities related to purchasing and funds management. She also plays a key role in assuring
        smooth daily lab operations.<br><a href="mailto:janet.yau@ucsf.edu">contact: janet.yau@ucsf.edu</a>
      </p>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h3 class="team-header">Adam Santaniello</h3>
      <h6 class="team-subheader">Database Manager</h6>
      <p><%= image_tag("adams.jpg", :class => "team-thumbnail")%>
        Adam has a B.S. in Engineering Science with Tau Beta Pi honors from Tufts University in Medford, MA. His prior experience includes software development and project management for consulting and financial
        services firms. He joined our lab in November 2007 and is leading the integration and enhancement of the lab's data sources.<br><a href="mailto:adam.santaniello@ucsf.edu">contact: adam.santaniello@ucsf.edu</a>
      </p>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h3 class="team-header">Adam Renschen</h3>
      <h6 class="team-subheader">Data Systems Analyst</h6>
      <p><%= image_tag("adamr.jpg", :class => "team-thumbnail")%>
        Adam Renschen joined the Genetics Laboratory in October 2016 as a web developer and member of the data management team. He has designed, built, and deployed websites, databases, and API’s to securely make research
        data available to remote consumers. He assists with the management of the laboratory databases and provides general IT support.<br><a href="mailto:adam.renschen@ucsf.edu">contact: adam.renschen@ucsf.edu</a>
      </p>
    </div>
  </div>



</div>

app/views/layouts/_footer.html.erb
<div class="container-fluid" id="footer-container">
  <div class="row">
    <div class="col-lg-4 offset-lg-1" id="footer-content">
      <%= link_to "Website Maintained by UCSF MS Data Coordination Core", new_user_session_path, :class => "footer-link" %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="container-fluid" id="header-container">

  <div class="row" id="top-row">
    <div class="col-lg-3 offset-lg-1 top-row-col">
      <%= link_to "University of California, San Francisco", 'https://www.ucsf.edu/', :target => :blank %>
    </div>
    <div class="col-lg-4 offset-lg-4 top-row-col">
      <%= link_to "About UCSF", 'https://www.ucsf.edu/about/ucsf-overview', :target => :blank %>
      <%= link_to "Search UCSF", 'https://www.ucsf.edu/search', :target => :blank %>
      <%= link_to "UCSF Medical Center", 'https://www.ucsfhealth.org/', :target => :blank %>
    </div>
  </div>

<br>

  <nav class="navbar  sticky-top navbar-expand-lg navbar-light" id="navmenu">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to "Multiple Sclerosis Genetics Research Laboratory", root_path, :class => 'navbar-brand' %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav ml-auto">
        <li class=<% if params[:controller] == 'home' && params[:action] == 'index' %>"navbar-item navbar-item-active"<% else %>"navbar-item"<% end %> >
          <%= link_to "Home", root_path, :class => "nav-link nav-nav-link nav-menu-item" %>
        </li>
        <li class=<% if params[:controller] == 'home' && params[:action] == 'team' %>"navbar-item navbar-item-active"<% else %>"navbar-item"<% end %> >
          <%= link_to "Team", team_path, :class => "nav-link nav-nav-link nav-menu-item" %>
        </li>
        <li class=<% if params[:controller] == 'home' && params[:action] == 'research' %>"navbar-item navbar-item-active"<% else %>"navbar-item"<% end %> >
          <%= link_to "Research", research_path, :class => "nav-link nav-nav-link nav-menu-item" %>
        </li>
        <li class=<% if params[:controller] == 'home' && params[:action] == 'publications' %>"navbar-item navbar-item-active"<% else %>"navbar-item"<% end %> >
          <%= link_to "Publications", publications_path, :class => "nav-link nav-nav-link nav-menu-item" %>
        </li>
        <li class=<% if params[:controller] == 'home' && params[:action] == 'jobs' %>"navbar-item navbar-item-active"<% else %>"navbar-item"<% end %> >
          <%= link_to "Join Us", jobs_path, :class => "nav-link nav-nav-link nav-menu-item" %>
        </li>
        <li class="navbar-item">
          <%= link_to "Biorepository", "https://msgenetics.ucsf.edu/biorepository", :target => :blank, :class => "nav-link nav-nav-link nav-menu-item" %>
        </li>
        <% if current_user %>
          <li class="navbar-item">
            <%= link_to "Admin", rails_admin_path, :class => "nav-link nav-nav-link nav-menu-item" %>
          </li>
        <% end %>
      </ul>
    </div>

  </nav>
</div>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UCSF Multiple Sclerosis Genetics Research Laboratory</title>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128939674-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-128939674-2');
    </script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  </head>

  <body>
  <%= render 'layouts/header' %>
    <%= yield %>
  <%= render 'layouts/footer' %>
  </body>
</html>